name: "Merong"
version: "1.0.0"
slug: "merong"
description: "Merong을 표시하는 재미있는 애드온"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
init: false
ports:
  8040/tcp: 8040
map:
  - config:rw
webui: "http://[HOST]:[PORT]:8040/"
image: "cece0719/merong-{arch}" 