name: Hello World
version: "1.0.0"
slug: hello_world
description: A simple Hello World add-on for Home Assistant
url: https://github.com/cece0719/ha-addons
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web interface
webui: http://[HOST]:[PORT:8099]
options:
  message: "Hello World!"
schema:
  message: str
