name: "Hello World"
version: "1.0.0"
slug: "hello-world"
description: "포트 8030에서 Hello World를 표시하는 간단한 애드온"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
init: false
ports:
  8030/tcp: 8030
map:
  - config:rw
  - ssl:ro
webui: "http://[HOST]:[PORT]:8030/" 