name: Build and Deploy Add-ons

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: [hello-world, merong]
        arch: [aarch64, amd64, armhf, armv7, i386]
        exclude:
          - addon: hello-world
            arch: armhf
          - addon: merong
            arch: armhf

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ matrix.addon }}
        platforms: linux/${{ matrix.arch }}
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ matrix.addon }}-${{ matrix.arch }}:latest
          ghcr.io/${{ github.repository_owner }}/${{ matrix.addon }}-${{ matrix.arch }}:${{ github.sha }}
        build-args: |
          BUILD_FROM=ghcr.io/hassio-addons/base/${{ matrix.arch }}:14.0.0 